config/routes.rb
Rails.application.routes.draw do
  resources :rides
  resources :profiles
  devise_for :users
  get 'page/navigate'
  get 'page/about'
  get 'page/profile'
  get 'page/contact'
  post 'page/contact'
  get 'page/rides'
  get 'page/home'
  get 'page/services'

  root 'page#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  # has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  has_attached_file :photo, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100#" }, default_url: "avatar_missing_original.jpg"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

  crop_attached_file :photo
  #crop_attached_file :snapshot, :aspect => "16:9"

  #validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

end

app/models/ride.rb
class Ride < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def navigate
  end

  def contact
    @name = params[:name]
    @email = params[:email]
    @subject = params[:subject]
    @message = params[:message]
   # @submit = params[:submit]
    @commit = params[:commit]


    @all = params[:all]
    if @commit == "Submit"
      ContactMailer.contact_email(@name, @email, @subject, @message).deliver_now
      redirect_to page_home_url, notice: 'Your message was successfully sent.'
      end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.exists?( :id => params[:id])
    if @profile
      set_profile
    else
      redirect_to new_profile_path
    end
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:fullname, :age, :email, :major, :gender, :schoolName, :smoke, :pet, :drive, :bio, :avatar, :photo)
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/new
  def new
    @ride = Ride.new
  end

  # GET /rides/1/edit
  def edit
  end

  # POST /rides
  # POST /rides.json
  def create
    @ride = Ride.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to @ride, notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: @ride }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rides/1
  # PATCH/PUT /rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to @ride, notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: @ride }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rides/1
  # DELETE /rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ride
      @ride = Ride.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ride_params
      params.require(:ride).permit(:author, :starting_location, :ending_location, :departure_date, :return_date, :available_seats, :estimated_cost, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AgileDev</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">

</head>
<body>



<%= render 'shared/header' %>

<%= render 'shared/main_navigation' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>




<%= yield %>
<%= render 'shared/footer_navigation' %>



</body>
</html>

app/views/page/about.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-8 content">
          <h1 class="page-title">About Us</h1>
          <div>
            <h2 class="sub-title">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis</h2>
          </div>

          <ul class="row">
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("house.jpg", alt:"Ez", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Ez Layata</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("slide3.jpg", alt:"Nate", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Nathan</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat volupt porro atem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">

                <%= image_tag("slide1.jpg", alt:"Terry", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Terry</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
          </ul>

          <ul class="row">
            <li class="columns large-4">
                <div class="img-wrapper">

                <%= image_tag("ShellyM_opt.jpg", alt:"", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Shelly</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat porro voluptatem</p>
            </li>
            <li class="columns large-4">
              <div class="img-wrapper">
                <%= image_tag("dylan.jpg", alt:"", class:"th about-image")%>
              </div>
              <h3 class="employer-name">Dylan</h3>
              <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat volupt porro atem</p>
            </li>

          </ul>
        </div>
        <div class="columns sidebar large-4 ">
          <h1 class="page-title">Our Acheivements</h1>
          <ul>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
            <li><a href="#">dolorem ipsum quia dolor sit amet</a></li>
            <li><a href="#">sed quia non numquam eius modi tempora </a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/page/contact.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-12 content ">
          <h1 class="page-title">Contact Us</h1>
          <div>
            <h2 class="sub-title">You can reach CollegeRides.com Customer Service from 8:00am to 6:00pm (Pacific Time) every weekday by submitting the form below!</h2>
          </div>

          <div class="row contact-form">
            <div class="columns large-8">

              <!--<form id="contact-form" method="post" action="#">
              <input type="text" name="name" placeholder="Name:">
              <input type="text" name="email" placeholder="Email:">
              <input type="text" name="subject" placeholder="Subject:">
              <textarea  name="message" placeholder="Message:"></textarea>
              <input type="submit" class="button" name="submit" value="send">
              </form>-->

              <%= form_tag do %>
                <%= text_field_tag 'name', @name, placeholder: 'Name:' %>
                <%= text_field_tag 'email', @email, placeholder: 'Email:' %>
                <%= text_field_tag 'subject', @subject, placeholder: 'Subject:' %>
                <%= text_area_tag 'message', @message, placeholder: 'Message'  %>
                <%= submit_tag 'Submit', class: 'contactTextBox' %>
              <% end %>


            </div>
            <div class="columns large-4">
              <div id="map_canvas"></div>
              <ul class="vcard">
                <li class="fn">FANTASTIC 5</li>
                <li class="street-address">255, Willson Street,Caulfield</li>
                <li class="locality">U.S.A</li>
                <li><span class="state">Washington</span>, <span class="zip">99212</span></li>
                <li class="email"><span>Email:</span>needarideWebmaster@gmail.com</li>
                <li class="telephone"><span>Tel:</span>(509)3456789, (509)3456079, (509)2341234</li>
                <li class="fax"><span>Tel:</span>1800-726-1924</li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row collapse">
          <div class="columns large-12"> </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/home.html.erb
<div class="wrapper">
    <div class="tagline-row">
      <div class="row tagline">
        <div class="columns large-12">
          <h2 class="center">
            Tincidunt. ac urna urna facilisis etiam platea ac phasellus vut
            pulvinar dolor porta augue montes odio dapibus elementum augue ultricies quis.</h2>
        </div>
      </div>
    </div>
    <div class="service-box">
      <div class="row service">
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup1.jpg", alt:"") %></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup2.jpg", alt:"") %></p>
            <h1>Phasell pulvinar magna</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
        <div class="columns large-4">
          <div class="box">
            <p> <%= image_tag("threeup3.jpg", alt:"") %></p>
            <h1>Lorem ipsum sit dolor esm</h1>
            <p>cum magna diam Duis amagna augue natoque odion nisi sed magna nascetur turpis inet sed parturient cum velit lacus Magna facilisis et cursus montes Turpisinet magnis parturient turpis magna turpis habitasse integ ultricies odion adipiscing eros nisi nunc aliquet lorem ipsum sites dolor esme turpis magna augue odio nisi phasellus pulvinar </p>
          </div>
        </div>
      </div>
    </div>



  </div>

app/views/page/rides.html.erb
<div class="wrapper">
  <div class="row content-wrapper">
    <div class="columns large-12">
      <div class="row">
        <div class="columns large-8 content">
          <h1 class="page-title">Blog Posts</h1>
          <p><b>Egestas aliquam vel ultrices integer</b>, ut sit pellentesque, et montes, turpis phasellus mauris porta <a href="#">parturient</a> platea pulvinar risus, lectus? Pid! Elementum sociis nunc sit! Dolor in eu ut placerat pellentesque, platea est risus etiam, dolor! Nec, penatibus odio scelerisque elementum pulvinar urna, dis nec vel nunc ut mid! In eros magna vel urna a platea proin, in tortor ultricies, et egestas amet, pellentesque ac, sit est ac integer ut cum porttitor penatibus, sed purus odio! Mauris nec? Quis, facilisis, tempor magna in vel lacus, cras risus, vel montes penatibus ultrices, aenean penatibus, nec lectus lacus penatibus? Egestas duis. Diam phasellus, integer in etiam sociis porta turpis proin in? Ridiculus! Turpis mauris placerat. Tincidunt in scelerisque diam mus egestas? Augue mauris. Augue etiam. Porta? Cum sed platea, nunc elit ultricies phasellus auctor augue aliquam tempor. Amet velit, adipiscing sed ac dictumst penatibus aliquam, parturient, purus. Enim nec augue mauris elementum cras.</p>
          <p>Dolor amet amet lectus phasellus, dolor aliquam. Nascetur arcu urna placerat, mid, elit adipiscing parturient nec ac dolor amet. Velit? Augue enim nisi phasellus velit, sit nunc elit natoque lacus, mus et ac vut mattis? Eu pulvinar pulvinar et, in habitasse, lundium, ridiculus? Arcu, ultrices, amet augue, ac pulvinar urna cum, turpis pid, eu. Ac porttitor, ut aliquam in? Ridiculus ac. Urna augue pid tortor porttitor vut, amet, enim ut turpis, sociis dignissim, augue sit porta scelerisque, in lectus aliquam vut habitasse ac? Rhoncus, placerat! Eros nec tincidunt ultrices scelerisque lorem. Sed diam mauris diam egestas? Amet in, mauris, nunc sociis scelerisque, sed eu, et mus, pulvinar, velit et facilisis lacus a aliquam non ut, sit porta? Diam ultricies? Placerat ut auctor urna adipiscing sit, quis rhoncus pulvinar integer sed proin? Porta penatibus magna, elementum, lorem nisi, elit adipiscing, mauris, porta egestas pid, vut sed arcu tristique, rhoncus sit.</p>
        </div>
        <div class="columns large-4 content sidebar">
          <h1 class="page-title services">Our Services</h1>
          <ul>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
            <li class="bullet"><a href="#">Purus magnis augue adipiscing mid magna</a></li>
            <li class="bullet"><a href="#">Amet dignissim natoque, dignissim lacus</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <h2>Edit Your Profile Settings</h2>
      <div class="field">
        <%= f.label :major %>
        <%= f.text_field :major %>
        <%= f.label :fullname %>
        <%= f.text_field :fullname %>

        <%= f.label :age %>
        <%= f.number_field :age %>

        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :schoolName %>
        <%= f.text_field :schoolName %>

        <%= f.label :bio %>
        <%= f.text_area :bio %>

        <%= f.label :photo %>
        <!--<#%= f.file_field :photo %>-->
            <!--<#%= f.cropbox :photo %>-->
            <!--<#%= f.crop_preview :photo %>-->
            <!--<#%= f.submit 'Save' %>-->



      </div>
      <div class="field gender-field">
        <%= f.label :gender %><br>
        <%= radio_button( 'profile', :gender, 'Female') %>
        <%= label_tag( 'Female') %><br>
        <%= radio_button( 'profile', :gender, 'Male') %>
        <%= label_tag( 'Male') %><br><br>

          <%= f.label :smoke %><br>
          <%= f.check_box :smoke %>

          <%= f.label :pet %><br>
          <%= f.check_box :pet %>

          <%= f.label :drive %><br>
          <%= f.check_box :drive %>


      </div>


      <!--<div class="field">-->
        <%#= f.label :avatar %><br>
        <!--<%#= f.text_field :avatar %>-->
      <!--</div>-->

      <div class="actions">
        <%= f.submit %>
      </div>

<% end %>

app/views/profiles/edit.html.erb
<div class="wrapper">
    <h1>Editing Profile</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @profile %> |
    <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Age</th>
      <th>Email</th>
      <th>Major</th>
      <th>Gender</th>
      <th>Schoolname</th>
      <th>Smoke</th>
      <th>Pet</th>
      <th>Drive</th>
      <th>Bio</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.fullname %></td>
        <td><%= profile.age %></td>
        <td><%= profile.email %></td>
        <td><%= profile.major %></td>
        <td><%= profile.gender %></td>
        <td><%= profile.schoolName %></td>
        <td><%= profile.smoke %></td>
        <td><%= profile.pet %></td>
        <td><%= profile.drive %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.avatar %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<div class="wrapper">
  <div class="new_user">
  <h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>
    </div>
</div>

app/views/profiles/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<div class="wrapper">


  <div id="w">
    <div id="content" class="clearfix">
      <div id="userphoto">
        <%=  image_tag @profile.photo.url(:large), class:"img_avatar" %>
        <%#= image_tag("house.jpg", alt:"Ez", class:"th about-image")%>
      </div>
      <div class="user_info">


        <div class="this2">   <h1 style="font-size: 4em;color: #3db2e1;">  <%= @profile.fullname %></h1>
        <h3> <strong>Age:</strong>
          <%= @profile.age %></h3>

        <h3> <strong>Email:</strong>
          <%= @profile.email %></h3>

        <h3> <strong>Schoolname:</strong>
          <%= @profile.schoolName %></h3>

        <h3><strong>Major:</strong>
          <%= @profile.major %></h3>

        <h3><strong>Gender:</strong>
          <%=  @profile.gender %></h3>
        <!-- SIDEBAR BUTTONS -->
        <button type="button" >Follow</button>
        <button type="button" >Message</button>

        <!-- END SIDEBAR BUTTONS -->
      </div>
      </div>
      <nav id="profiletabs">
        <ul class="clearfix">
          <li><a href="#bio" class="sel">Profile</a></li>
          <li><a href="#activity">Activity</a></li>
          <li><a href="#friends">Friends</a></li>
          <li><a href="#settings">Settings</a></li>
        </ul>
      </nav>

      <section id="bio">


        <p>
          <strong>Smoke:</strong>
          <%= @profile.smoke %>
        </p>

        <p>
          <strong>Pet:</strong>
          <%= @profile.pet %>
        </p>

        <p>
          <strong>Drive:</strong>
          <%= @profile.drive %>
        </p>

        <p>
          <strong>Bio:</strong>
          <%= @profile.bio %>
        </p>

        <%= link_to 'Edit', edit_profile_path(@profile) %> |
        <%= link_to 'Back', page_home_path %>



      </section>

      <section id="activity" class="hidden">
        <p>Activity Tab:</p>


      </section>

      <section id="friends" class="hidden">
        <p>Friends Tab:</p>


      </section>

      <section id="settings" class="hidden">


        <%= render 'form' %>

        <%= link_to 'Show', @profile %> |
        <%= link_to 'Back', profiles_path %>
      </section>
    </div><!-- @end #content -->
  </div><!-- @end #w -->
  <script type="text/javascript">
    $(function(){
      $('#profiletabs ul li a').on('click', function(e){
        e.preventDefault();
        var newcontent = $(this).attr('href');

        $('#profiletabs ul li a').removeClass('sel');
        $(this).addClass('sel');

        $('#content section').each(function(){
          if(!$(this).hasClass('hidden')) { $(this).addClass('hidden'); }
        });

        $(newcontent).removeClass('hidden');
      });
    });
  </script>
</div>

app/views/rides/edit.html.erb
<h1>Editing Ride</h1>

<%= render 'form' %>

<%= link_to 'Show', @ride %> |
<%= link_to 'Back', rides_path %>

app/views/rides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rides</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Starting location</th>
      <th>Ending location</th>
      <th>Departure date</th>
      <th>Return date</th>
      <th>Available seats</th>
      <th>Estimated cost</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rides.each do |ride| %>
      <tr>
        <td><%= ride.author %></td>
        <td><%= ride.starting_location %></td>
        <td><%= ride.ending_location %></td>
        <td><%= ride.departure_date %></td>
        <td><%= ride.return_date %></td>
        <td><%= ride.available_seats %></td>
        <td><%= ride.estimated_cost %></td>
        <td><%= ride.details %></td>
        <td><%= link_to 'Show', ride %></td>
        <td><%= link_to 'Edit', edit_ride_path(ride) %></td>
        <td><%= link_to 'Destroy', ride, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ride', new_ride_path %>

app/views/rides/new.html.erb
<h1>New Ride</h1>

<%= render 'form' %>

<%= link_to 'Back', rides_path %>

app/views/rides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @ride.author %>
</p>

<p>
  <strong>Starting location:</strong>
  <%= @ride.starting_location %>
</p>

<p>
  <strong>Ending location:</strong>
  <%= @ride.ending_location %>
</p>

<p>
  <strong>Departure date:</strong>
  <%= @ride.departure_date %>
</p>

<p>
  <strong>Return date:</strong>
  <%= @ride.return_date %>
</p>

<p>
  <strong>Available seats:</strong>
  <%= @ride.available_seats %>
</p>

<p>
  <strong>Estimated cost:</strong>
  <%= @ride.estimated_cost %>
</p>

<p>
  <strong>Details:</strong>
  <%= @ride.details %>
</p>

<%= link_to 'Edit', edit_ride_path(@ride) %> |
<%= link_to 'Back', rides_path %>

app/views/shared/_header.html.erb
<head>

</head>

app/views/shared/_main_navigation.html.erb
<div class="row">
  <div class="columns large-12  header-logo">
    <!---->
    <!--<a href="home.html"> <%= image_tag("logo.png", alt:"") %></a>-->

  </div>

  <div id="axis" class="two">
    <%= image_tag("logo.png", alt:"moving_car", class:"object van move-left", width:"80", height:"80" ) %>
  </div>








  <div class="columns large-12">




          <div id='cssmenu'>
            <ul class="sf-menu large-12">
              <li><%= link_to 'HOME', page_home_path %></li>
              <li><%= link_to 'ABOUT US' , page_about_path%></li>
              <% if user_signed_in? %>
                <li><%= link_to 'PROFILE' , profile_path(current_user.id) %></li>
              <% else %>
                  <li><%= link_to 'PROFILE' , new_user_session_path %></li>
              <% end %>
              <li><%= link_to 'SERVICES' , page_services_path %></li>
              <li><%= link_to 'CONTACT US' , page_contact_path %></li>
              <li><%= link_to 'RIDES', rides_path %></li>
              <% if user_signed_in? %>
                  <li>  <%= link_to 'Logout' , destroy_user_session_path, method: "delete"%></li>
              <% else %>
                  <li><%= link_to 'Login/Sign-Up' , new_user_session_path%></li>
              <% end %>
            </ul>
          </div>



  </div>

</div>